
name: Build Android APK
  # .github/workflows/main.yml
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *

      - name: Upload to gdrive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.credentials }}
          filename: "archive.zip"
          folderId: ${{ secrets.folderId }}
          name: "${{ env.TAG }}.zip" # optional string
          overwrite: "true" # optional boolean
