# This is a basic workflow to help you get started with Actions

name: Build Android APK

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      branches:
        description: 'Write branch you want to build'
        required: true
        type: string
      environment:
        description: 'Choose environment you want to build'
        required: true
        options:
          - staging
          - development
          - production
        type: choice
        default: 'development'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set Test Variable
        id: set-variable
        run: |
          if [ ${{ github.event.inputs.environment }} == 'development' ]; then
              echo "Build APK with development environment"
              echo "assemble=assembleDebug" >> $GITHUB_ENV
              echo "apk=app-debug" >> $GITHUB_ENV
            
          elif [ ${{ github.event.inputs.environment }} == 'production' ]; then
              echo "Build APK with production environment"
              echo "assemble=assembleRelease" >> $GITHUB_ENV
              echo "apk=app-release" >> $GITHUB_ENV
          else
              echo "Build APK with staging environment"
              echo "assemble=assembleRelease" >> $GITHUB_ENV
              echo "apk=app-release" >> $GITHUB_ENV
          fi
        shell: bash
      - name: Read exported variable
        run: |
          echo "ENV: ${{ env.assemble }}"
          echo "ENV: ${{ env.apk }}"
          
      
      
